### ISSUE TITLE
Tool recommended for iPad pro?

### ISSUE THREAD

**Issue by arkilis** [Siilwyn/awesome-pixel-art#26]

**Comment by Siilwyn** [comment]
Great question hope anybody else can chime in on this since I don't have an iPad.

Did a bit of searching and found [Pixaki](https://apps.apple.com/us/app/pixaki-pixel-art-studio/id1130919277) to be one of the better apps. But still not awesome? Reviews mention some lacking features and random crashes.

**Comment by arkilis** [comment]
thanks~ Already bought this one, seems like not quite good to use.

**Comment by Siilwyn** [comment]
Alright thanks for the update!

That's a bummer, I'll keep this issue open for anybody to make suggestions.

**Comment by claromes** [comment]
@arkilis You can try [Pixel Studio](https://apps.apple.com/br/app/pixel-studio-for-pixel-art/id1404203859).
